// TITAN PRO · V8 — Font Awesome icon wrapper.
// Tree-shakeable: import only the icons we use, in this single file.

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faCog,
  faClose,
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faBolt,
  faCheck,
  faCamera,
  faShieldHalved,
  faCrown,
  faGripLines,
  faXmark,
  faWandSparkles,
  faPaperPlane,
  faComment,
  faComments,
  faTrash,
  faRefresh,
  faFloppyDisk,
  faKey,
  faChartLine,
  faChartColumn,
  faUsers,
  faEye,
  faHeart,
  faClock,
  faCalendar,
  faCalendarDays,
  faShare,
  faCopy,
  faLink,
  faDownload,
  faPlay,
  faPause,
  faBars,
  faCircleCheck,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleInfo,
  faArrowUp,
  faArrowDown,
  faUpRightAndDownLeftFromCenter,
  faBullseye,
  faHashtag,
  faHandshake,
  faLightbulb,
  faFlagCheckered,
  faListCheck,
  faLocationDot,
  faChartBar,
  faArrowTrendUp,
  faArrowTrendDown,
  faGauge,
  faStar,
  faFire,
  faRocket,
  faBoltLightning,
  faCircleNodes,
  faCompass,
  faMapPin,
  faTrophy,
  faMedal,
  faCertificate,
  faArrowUpWideShort,
  faChartPie,
  faLifeRing,
  faEnvelope,
  faCircleXmark,
} from '@fortawesome/free-solid-svg-icons';

// Build a lookup map so we can do <Icon name="cog" /> anywhere without
// importing the icon set per-file.
const ICONS = {
  cog: faCog,
  close: faXmark,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  arrowUpRight: faArrowUpRightFromSquare,
  bolt: faBolt,
  check: faCheck,
  camera: faCamera,
  sword: faShieldHalved,
  shield: faShieldHalved,
  crown: faCrown,
  grip: faGripLines,
  wand: faWandSparkles,
  paperPlane: faPaperPlane,
  comment: faComment,
  comments: faComments,
  trash: faTrash,
  refresh: faRefresh,
  save: faFloppyDisk,
  key: faKey,
  chart: faChartLine,
  chartLine: faChartLine,
  chartColumn: faChartColumn,
  chartBar: faChartBar,
  chartPie: faChartPie,
  users: faUsers,
  eye: faEye,
  heart: faHeart,
  clock: faClock,
  calendar: faCalendar,
  calendarDays: faCalendarDays,
  share: faShare,
  copy: faCopy,
  link: faLink,
  download: faDownload,
  play: faPlay,
  pause: faPause,
  bars: faBars,
  circleCheck: faCircleCheck,
  circleExclamation: faCircleExclamation,
  triangleExclamation: faTriangleExclamation,
  circleInfo: faCircleInfo,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  expand: faUpRightAndDownLeftFromCenter,
  bullseye: faBullseye,
  hashtag: faHashtag,
  handshake: faHandshake,
  lightbulb: faLightbulb,
  flagCheckered: faFlagCheckered,
  listCheck: faListCheck,
  locationDot: faLocationDot,
  mapPin: faMapPin,
  trendUp: faArrowTrendUp,
  trendDown: faArrowTrendDown,
  gauge: faGauge,
  star: faStar,
  fire: faFire,
  rocket: faRocket,
  boltLightning: faBoltLightning,
  circleNodes: faCircleNodes,
  compass: faCompass,
  trophy: faTrophy,
  medal: faMedal,
  certificate: faCertificate,
  arrowUpWideShort: faArrowUpWideShort,
  'life-buoy': faLifeRing,
  lifeBuoy: faLifeRing,
  mail: faEnvelope,
  envelope: faEnvelope,
  x: faCircleXmark,
};

/**
 * <Icon name="cog" size={14} /> — drop-in replacement for emoji/text icons.
 * Defaults to `size` matching the font-size of the surrounding text.
 */
export default function Icon({ name, size = 14, className = '', ...rest }) {
  const icon = ICONS[name];
  if (!icon) {
    if (typeof console !== 'undefined') {
      console.warn(`[Icon] unknown name "${name}"`);
    }
    return null;
  }
  return <FontAwesomeIcon icon={icon} fontSize={size} className={className} {...rest} />;
}
